.TH RARY_STRING_write 3 2021-03-03 Rary "library's man page"

.SH NAME

RARY_STRING_write \- Write a message to a file

.SH SYNOPSIS

.B #include <rary/rary.h>

.BI "int RARY_STRING_write(const char " *file ", const char " *message ", const char " *mode );

.SH DESCRIPTION

Write 
.I message
to
.IR file .

Mode should be
.I \*(lqw\*(rq
to truncate the file, or
.I \*(lqa\*(rq
to append to the file (same as 
.IR fopen ()).

.SH RETTURN VALUE

Return
.I RARY_OK
on success. On error, return
.IR RARY_FAIL .

.SH SEE ALSO
RARY_STRING_create(3), RARY_STRING_read(3), RARY_STRING_split(3)